In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
from sqlalchemy import create_engine

In [4]:
engine = create_engine("postgresql://postgres:postgres@localhost:5433/ny_taxi");

In [6]:
df = pd.read_csv("green_tripdata_2019-10.csv", nrows=100)

In [7]:
df

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1,112,196,1,5.88,18.0,0.50,0.5,0.00,0.0,NaN,0.3,19.30,2,1,0.0
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1,43,263,1,0.80,5.0,3.25,0.5,0.00,0.0,NaN,0.3,9.05,2,1,0.0
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1,255,228,2,7.50,21.5,0.50,0.5,0.00,0.0,NaN,0.3,22.80,2,1,0.0
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1,181,181,1,0.90,5.5,0.50,0.5,0.00,0.0,NaN,0.3,6.80,2,1,0.0
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1,97,188,1,2.52,10.0,0.50,0.5,2.26,0.0,NaN,0.3,13.56,1,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2019-10-01 00:02:53,2019-10-01 00:14:32,N,1,126,74,1,3.10,12.0,0.50,0.5,0.00,0.0,NaN,0.3,13.30,1,1,0.0
96,2,2019-10-01 00:18:45,2019-10-01 00:29:23,N,1,42,74,1,1.64,9.5,0.50,0.5,0.00,0.0,NaN,0.3,10.80,2,1,0.0
97,2,2019-10-01 00:41:32,2019-10-01 00:52:51,N,1,75,42,1,3.17,11.5,0.50,0.5,1.50,0.0,NaN,0.3,14.30,1,1,0.0
98,2,2019-10-01 00:36:54,2019-10-01 00:54:20,N,1,92,179,1,5.48,19.5,0.50,0.5,0.00,0.0,NaN,0.3,20.80,2,1,0.0
99,2,2019-10-01 00:21:27,2019-10-01 00:26:59,N,1,129,129,1,1.02,6.0,0.50,0.5,0.00,0.0,NaN,0.3,7.30,2,1,0.0

In [8]:
print(pd.io.sql.get_schema(df, "green_tripdata" ))

CREATE TABLE "green_tripdata" (
"VendorID" INTEGER,
  "lpep_pickup_datetime" TEXT,
  "lpep_dropoff_datetime" TEXT,
  "store_and_fwd_flag" TEXT,
  "RatecodeID" INTEGER,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "ehail_fee" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "payment_type" INTEGER,
  "trip_type" INTEGER,
  "congestion_surcharge" REAL
)

In [9]:
df.lpep_pickup_datetime = pd.to_datetime(df.lpep_pickup_datetime)

In [10]:
df.lpep_dropoff_datetime = pd.to_datetime(df.lpep_dropoff_datetime)

In [11]:
print(pd.io.sql.get_schema(df, "green_tripdata" ))

CREATE TABLE "green_tripdata" (
"VendorID" INTEGER,
  "lpep_pickup_datetime" TIMESTAMP,
  "lpep_dropoff_datetime" TIMESTAMP,
  "store_and_fwd_flag" TEXT,
  "RatecodeID" INTEGER,
  "PULocationID" INTEGER,
  "DOLocationID" INTEGER,
  "passenger_count" INTEGER,
  "trip_distance" REAL,
  "fare_amount" REAL,
  "extra" REAL,
  "mta_tax" REAL,
  "tip_amount" REAL,
  "tolls_amount" REAL,
  "ehail_fee" REAL,
  "improvement_surcharge" REAL,
  "total_amount" REAL,
  "payment_type" INTEGER,
  "trip_type" INTEGER,
  "congestion_surcharge" REAL
)

In [15]:
for chunk in pd.read_csv("green_tripdata_2019-10.csv", chunksize=500):
    chunk.lpep_pickup_datetime = pd.to_datetime(chunk.lpep_pickup_datetime)
    chunk.lpep_dropoff_datetime = pd.to_datetime(chunk.lpep_dropoff_datetime)
    chunk.to_sql(name="green_tripdata", con=engine, if_exists='append', index=False)
    print(f"Inserted {len(chunk)} rows")

Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows

/var/folders/3m/ydc1mdn56g99h7vft_wzwk640000gn/T/ipykernel_46492/245962755.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  chunk.lpep_dropoff_datetime = pd.to_datetime(chunk.lpep_dropoff_datetime)

Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 500 rows
Inserted 386 rows